version: '3.9'

services:
  postgres:
    platform: linux/amd64
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    networks:
      - mynet
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  springbootapp:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image : matheusbattiston/account_app:latest
    container_name: springbootapp
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/my_database
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_password
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  pgdata:
