spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/my_database
    username: my_user
    password: my_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
