spring:
  datasource:
    url: jdbc:postgresql://matheusbattistonrds.cbgy4ye6ky3l.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
